name: Android Build Cloud
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android

      # ON FORCE LE BUILD EN MODE DEBUG ICI 
      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Build APK (Debug)
        run: cordova build android --debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon-Application-APK
          # On cherche absolument partout dans tous les dossiers
          path: "**/*.apk"
