name: Android Build Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Android SDK (with license acceptance)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Add Android platform
        run: cordova platform add android

      - name: Create google-services.json from secret
        # On suppose que le secret contient le JSON brut (non encodé)
        run: printf '%s' "${{ secrets.GOOGLE_SERVICES_JSON }}" > google-services.json

      - name: Copy Firebase config to correct locations
        run: |
          mkdir -p platforms/android/app/src/debug
          cp google-services.json platforms/android/app/
          cp google-services.json platforms/android/app/src/debug/

      - name: Build APK (Debug)
        run: cordova build android --debug
        # good
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Max-it-OTP-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
