name: Android Build Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android --nosave || echo "Platform exists"

      # Décodage avec suppression forcée de tout caractère invisible
      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | tr -d '\n\r ' | base64 -d > google-services.json

      - name: Finalize Firebase Config
        run: |
          mkdir -p platforms/android/app/src/debug/
          cp google-services.json platforms/android/app/
          cp google-services.json platforms/android/app/src/debug/
          
          echo "--- DIAGNOSTIC DU FICHIER ---"
          ls -l google-services.json
          head -c 20 google-services.json
          echo -e "\n--- FIN DIAGNOSTIC ---"

      - name: Build APK (Debug)
        run: cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Max-it-OTP-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
